### ISSUE TITLE
Signing Bitcoin Cash transactions: BIP143 sighash type results in ECsignature error

### ISSUE THREAD

**Issue by k33rs** [BitGo/bitgo-utxo-lib#27]
Hello,
I'm trying to sign a Bitcoin Cash transaction using sighash type

`Transaction.SIGHASH_BITCOINCASHBIP143 = 0x40`

but this results in the following error

`[2019-03-07T17:57:52.111Z] Error: Invalid hashType 64
    at ECSignature.toScriptSignature (/app/node_modules/bitgo-utxo-lib/src/ecsignature.js:89:51)
    at /app/node_modules/bitgo-utxo-lib/src/transaction_builder.js:829:37
    at Array.some (<anonymous>)
    at TransactionBuilder.sign (/app/node_modules/bitgo-utxo-lib/src/transaction_builder.js:818:30)
    at TxBuilder.build (/app/node_modules/utxo/lib/TxBuilder.js:102:15)`

In ecsignature.js line 89 

`ECSignature.prototype.toScriptSignature = function (hashType) {`
`var hashTypeMod = hashType & ~0xc0`
`if (hashTypeMod <= 0 || hashTypeMod >= 4) throw new Error('Invalid hashType ' + hashType)`
`...` 

the check fails because hashTypeMod evaluates to zero.

Does the library support Bitcoin Cash signatures yet?

**Comment by argjv** [comment]
This should be working. Are you setting the correct `network` object in the transaction builder?

**Comment by k33rs** [comment]
I'm using Bitcoin Cash testnet:

`{
  "messagePrefix": "\u0018Bitcoin Signed Message:\n",
  "bech32": "tb",
  "bip32": {
    "public": 70617039,
    "private": 70615956
  },
  "pubKeyHash": 111,
  "scriptHash": 196,
  "wif": 239,
  "coin": "bch"
}`

and passing it to transaction builder.

Using the same code I can successfully build and broadcast transactions on bitcoin, litecoin and zcash testnets, signing transactions with hash type SIGHASH_ALL = 0x01.

Now, using the same hash type on bcash does not successfully sign the transaction, which gets refused by the node (missing inputs: -25), therefore I changed the hash type.

Can you reproduce the error by signing a transaction with hash type SIGHASH_BITCOINCASHBIP143 = 0x40?

**Comment by k33rs** [comment]
I've managed to sign and broadcast the transaction.

Using sighash type 0x65 (SIGHASH_ALL | SIGHASH_BITCOINCASHBIP143) solved the problem.
