### ISSUE TITLE
ZEC: z-addr generation & ZKP tx-builder examples

### ISSUE THREAD

**Issue by dmorris99** [BitGo/bitgo-utxo-lib#34]
Hi all,

Is anybody able please to provide a code example of what is required to;

(a) generate a ZEC z-addr (HDNode-derived) keyPair (my current t-addr code is below for reference)

```
    const entropySha256 = utils.sha256_shex(entropySeed)
    var root = bitgoUtxoLib.HDNode.fromSeedHex(entropySha256, network) // bitgo HDNode 
    ...
        const path = `m/44'/${meta.bip44_index}'/${accountNdx}'/${chainNdx}/${i}`
        const child = root.derivePath(path)
        var keyPair = child.keyPair // bitgo
        var wif = keyPair.toWIF()
```

(b) build a ZEC t->z (and/or z->z, z->t) transaction? (again, current t->t transparent tx code is below for reference)

```
const txb = new bitgoUtxoLib.TransactionBuilder(network)
txb.setVersion(bitgoUtxoLib.Transaction.ZCASH_SAPLING_VERSION) // sapling: v4
txb.setVersionGroupId(2301567109) // sapling
txb.setExpiryHeight(0)
for (var i = 0; i < res.inputs.length; i++) {
    txb.addInput(res.inputs[i].utxo.txid, res.inputs[i].utxo.vout)
}
res.outputs.forEach(output => {
    txb.addOutput(output.address, output.value)
})
for (var i = 0; i < res.inputs.length; i++) {
    var wif = addrPrivKeys.find(p => { return p.addr === res.inputs[i].utxo.address }).privKey
    var keyPair = bitgoUtxoLib.ECPair.fromWIF(wif, network)
    txb.sign(i, keyPair, '', bitgoUtxoLib.Transaction.SIGHASH_SINGLE, res.inputs[i].utxo.satoshis)
}
...
```

I'm unclear what additional ZPK proof generation needs to happen, how to do it if so, or if this is already supported internally in some way (it isn't evident to me that it does). Any inputs or assistance are greatly appreciated!

Thank you,
D.

**Comment by Xekyo** [comment]
Hello Dominic,
To my knowledge, the bitgo-utxo-lib only supports t-addresses for Zcash at this time.

**Comment by dmorris99** [comment]
Hi @Xekyo , thanks for confirming -- that's as I thought then. 

If I get anywhere in enabling z-addr tx-gen with a modified bitgo-utxo-lib, I'll update.
