### ISSUE TITLE
`fromBase58()` should pick the correct instead of always the last network object

### ISSUE THREAD

**Issue by Xekyo** [BitGo/bitgo-utxo-lib#36]
> The method `fromBase58()` can take an array of network objects, but when it does that, it just pops the last one, in this case, the `litecointest` one.

_Originally posted by @argjv in https://github.com/BitGo/bitgo-utxo-lib/pull/35#issuecomment-483931556_

Instead it should be picking the correct network by some sort of identifier.

**Comment by OttoAllmendinger** [comment]
@Xekyo @argjv 

to my understanding, we pick the *last correct* network object: 

https://github.com/BitGo/bitgo-utxo-lib/blob/1da46b908f5be59dd0c84f88770d6ad0c59f189f/src/hdnode.js#L67-L72

Looks fine to me
